#!/bin/bash

lsss
exit 0
#here it will exit at above, it won't execute(run) below command..
echo Hello
-----------------

Find I am root user or not before executing the script.

USER_ID=$(id -u)
if [ $USER_ID -ne 0 ]; then
   echo You are Non root user
   echo You can run this script as root user or with sudo
   exit 1
   fi


